### ISSUE TITLE
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <asset:stylesheet>: java/util/Objects

### ISSUE THREAD

**Issue by genkishen** [bertramdev/grails-asset-pipeline#390]
Hi there,

I was able to test my grail project and view it in a browser; however, as soon as package in a WAR file, this is the error shows in stacklog:

Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <asset:stylesheet>: java/util/Objects
     at org.codehaus.groovy.grails.web.pages.GroovyPage.throwRootCause(GroovyPage.java:527)
     at org.codehaus.groovy.grails.web.pages.GroovyPage.invokeTag(GroovyPage.java:470)
     at sun.reflect.GeneratedMethodAccessor139.invoke(Unknown Source)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:622)
     at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
     at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
     at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1111)
     at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
     at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66)
     at gsp_necadmin_layoutsmain_gsp$_run_closure1.doCall(gsp_necadmin_layoutsmain_gsp.groovy:27)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     at java.lang.reflect.Method.invoke(Method.java:622)
     at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
     at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)

I am wondering if you would know what's the issue of my WAR file?

Much appreciated!

Calvin

**Comment by davydotcom** [comment]
What is in your build.gradle file?

**Comment by genkishen** [comment]
i found the similar issue from another thread and the way for me to resolve it is to downgrade asset-pipeline to version 1.9.9, then i was able to create the WAR file and deploy to my Tomcat server.

**Comment by davydotcom** [comment]
Sounds like a version mismatch or conflict in your build
