### ISSUE TITLE
Grails Asset Pipeline Problem

### ISSUE THREAD

**Issue by muneerjava17** [bertramdev/grails-asset-pipeline#393]
I am getting this error when I am setting up the project on the new machine. For the old machines everything is okay. 

Grails application running at http://localhost:8080 in environment: development
ERROR:  Could not find a valid gem 'compass' (= 1.0.3), here is why:
          Unable to download data from https://rubygems.org/ - Received fatal alert: protocol_version (https://rubygems.org/specs.4.8.gz)
ERROR:  Could not find a valid gem 'chunky_png' (= 1.3.4), here is why:
          Unable to download data from https://rubygems.org/ - Received fatal alert: protocol_version (https://rubygems.org/specs.4.8.gz)
ERROR:  Could not find a valid gem 'compass-core' (= 1.0.3), here is why:
          Unable to download data from https://rubygems.org/ - Received fatal alert: protocol_version (https://rubygems.org/specs.4.8.gz)
ERROR:  Could not find a valid gem 'sass' (= 3.4.19), here is why:
          Unable to download data from https://rubygems.org/ - Received fatal alert: protocol_version (https://rubygems.org/specs.4.8.gz)
ERROR:  Could not find a valid gem 'fssm' (= 0.2.10), here is why:
          Unable to download data from https://rubygems.org/ - Received fatal alert: protocol_version (https://rubygems.org/specs.4.8.gz)
ERROR:  Could not find a valid gem 'ffi' (= 1.9.10), here is why:
          Unable to download data from https://rubygems.org/ - Received fatal alert: protocol_version (https://rubygems.org/specs.4.8.gz)
LoadError: no such file to load -- sass
               require at org/jruby/RubyKernel.java:1071
               require at /Users/muneer/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/1.7.18/a1be3e1790aace5c99614a87785454d875eb21c2/jruby-complete-1.7.18.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
               require at /Users/muneer/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/1.7.18/a1be3e1790aace5c99614a87785454d875eb21c2/jruby-complete-1.7.18.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53
                (root) at <script>:4
                <init> at SassProcessor.groovy:63
       processedStream at AbstractAssetFile.groovy:170
          fileContents at DirectiveProcessor.groovy:307
  serveUncompiledAsset at AssetPipeline.groovy:65
      doFilterInternal at AssetPipelineFilter.groovy:214
2018-10-18 12:15:29.838 ERROR --- [io-8080-exec-10] .a.c.c.C.[.[.[.[grailsDispatcherServlet] : Servlet.service() for servlet [grailsDispatcherServlet] in context with path [] threw exception [Filter execution threw an exception] with root cause

org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- sass
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
	at Kernel.require(/Users/muneer/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/1.7.18/a1be3e1790aace5c99614a87785454d875eb21c2/jruby-complete-1.7.18.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55)
	at Kernel.require(/Users/muneer/.gradle/caches/modules-2/files-2.1/org.jruby/jruby-complete/1.7.18/a1be3e1790aace5c99614a87785454d875eb21c2/jruby-complete-1.7.18.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53)
	at RUBY.(root)(<script>:4)
	at asset.pipeline.sass.SassProcessor.<init>(SassProcessor.groovy:63)
	at asset.pipeline.AbstractAssetFile.processedStream(AbstractAssetFile.groovy:170)
	at asset.pipeline.DirectiveProcessor.fileContents(DirectiveProcessor.groovy:307)
	at asset.pipeline.AssetPipeline.serveUncompiledAsset(AssetPipeline.groovy:65)
	at asset.pipeline.AssetPipelineFilter.doFilterInternal(AssetPipelineFilter.groovy:214)

**Comment by NunoSantana** [comment]
This issue is caused because openssl client doesn't support TLSv1.2. If you clear the cache in the old machines they will stop working too.

**Comment by davydotcom** [comment]
If you force bump the transitive dependency for jruby patch level you should be able to bypass this
